apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale-example-pod-deployment
  namespace: scale-example
  labels:
    app: scale-example-pod
spec:
  replicas: 30
  selector:
    matchLabels:
      app: scale-example-pod
  template:
    metadata:
      labels:
        app: scale-example-pod
    spec:
      containers:
        - name: scale-example-pod
          image: nginx
          resources:
            limits:
              memory: "200Mi"
              cpu: "200m"
            requests:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
